// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXNe7_AOkmRXQljqAn0xctAKbDZ2TrG2Y',
    appId: '1:597187162966:web:acd7028f17637ffac21cf7',
    messagingSenderId: '597187162966',
    projectId: 'c-box-community',
    authDomain: 'c-box-community.firebaseapp.com',
    storageBucket: 'c-box-community.appspot.com',
    measurementId: 'G-D60LQHCJ6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Z0u0wVb-TSl8l7vmREUj2jdqYpSKfbk',
    appId: '1:597187162966:android:cec0ae4e7e791099c21cf7',
    messagingSenderId: '597187162966',
    projectId: 'c-box-community',
    storageBucket: 'c-box-community.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY4mqzUczV-bUOcA5ckw60iPv-8qE4Zok',
    appId: '1:597187162966:ios:7648c7de0fb63983c21cf7',
    messagingSenderId: '597187162966',
    projectId: 'c-box-community',
    storageBucket: 'c-box-community.appspot.com',
    iosBundleId: 'com.example.cBox',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY4mqzUczV-bUOcA5ckw60iPv-8qE4Zok',
    appId: '1:597187162966:ios:7648c7de0fb63983c21cf7',
    messagingSenderId: '597187162966',
    projectId: 'c-box-community',
    storageBucket: 'c-box-community.appspot.com',
    iosBundleId: 'com.example.cBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXNe7_AOkmRXQljqAn0xctAKbDZ2TrG2Y',
    appId: '1:597187162966:web:57f94f887dfa3035c21cf7',
    messagingSenderId: '597187162966',
    projectId: 'c-box-community',
    authDomain: 'c-box-community.firebaseapp.com',
    storageBucket: 'c-box-community.appspot.com',
    measurementId: 'G-P6THHGY5M8',
  );

}