// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFSPBHkM497cbwbioedgtpE4TR_aA0Fdg',
    appId: '1:101240004651:web:46e05e0b9cfa7c31700a6e',
    messagingSenderId: '101240004651',
    projectId: 'c-box-38caf',
    authDomain: 'c-box-38caf.firebaseapp.com',
    storageBucket: 'c-box-38caf.appspot.com',
    measurementId: 'G-TF635JWTCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB56IA9FTmpwQx9HSrKXjnxMAOvCB_BAXw',
    appId: '1:101240004651:android:1542280358530761700a6e',
    messagingSenderId: '101240004651',
    projectId: 'c-box-38caf',
    storageBucket: 'c-box-38caf.appspot.com',
  );
}
